apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
spec:
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      serviceAccountName: catalog-serviceaccount
      containers:
      - name: catalog
        image: wbplayeconomy.azurecr.io/play.catalog:1.0.3
        imagePullPolicy: Always
        env:
          - name: ServiceSettings__MessageBroker
            value: SERVICEBUS
          - name: ServiceSettings__KeyVaultName
            value: wbplayeconomy
        resources:
          limits:
            memory: "128Mi"
            cpu: "150m"
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health/live
            port: 5000
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 5000
          initialDelaySeconds: 10          

---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  type: LoadBalancer
  selector:
    app: catalog
  ports:
  - port: 80
    targetPort: 5000

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: catalog-serviceaccount
  annotations:
    azure.workload.identity/client-id: 3f11e792-4cbb-499c-985d-bc500b2c990e
  labels:
    azure.workload.identity/use: "true"