microserviceName: "catalog"

image:
  repository: wbplayeconomy.azurecr.io/play.catalog
  tag: 1.0.4

envVariables:
  IdentitySettings__PathBase: /catalog-svc

resources:
  limits:
    memory: "256Mi"
    cpu: "300m"

container:
  port: 5000

identityClientId: 3f11e792-4cbb-499c-985d-bc500b2c990e